### ISSUE TITLE
Number of Parameters

### ISSUE THREAD

**Issue by pazadimo** [mahmoodlab/SurvPath#3]
Hi,

Thanks for the interesting work. Can you please share the total number of parameters or at least an estimation?
I may have misunderstood it, but I assume that there is a separate SNN block for each pathway. So, If we have 330 pathways here, the pathway tokenizer will have at least 330*256*256 parameters which is about 21 million. I appreciate your clarification. 

Thanks

**Comment by guillaumejaume** [comment]
The pathway-specific MLPs add a lot of parameters. Empirically, we didn't find it to be a limitation -- all trainings were conducted on a single 3090 GPU with 24GB of RAM.
