### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by sky-hqn** [mahmoodlab/SurvPath#5]
The storage location and required type of WSI do not seem to be shown in the code. If it's convenient for you, can you provide the complete data structure? Thank you very much

**Comment by ajv012** [comment]
SurvPath is not meant for processing WSI. You can use the CLAM toolkit (https://github.com/mahmoodlab/CLAM) to process WSI and store the patch features in a convenient location. SurvPath is meant to be used with H&E stained WSI only.

**Comment by ajv012** [comment]
yes, that is correct. WSI (.svs) are too large in size to work with directly, so you need to process them using CLAM (or any other similar toolkit) before you use SurvPath.
