### ISSUE TITLE
how is clinical information collected?

### ISSUE THREAD

**Issue by XiaoXueShengwangrui** [mahmoodlab/SurvPath#9]
Your work is great！ I am a novice in pathological image survival analysis, so I would like to know how the clinical information are collected correctly?

The information in [cbioportal](https://www.cbioportal.org/) is very complicated and messy. I am not sure whether I only need to extract the survival time.

<img width="1273" alt="image" src="https://github.com/mahmoodlab/SurvPath/assets/32757858/9c3c2714-5bff-4c4a-919e-0c1b1cef9d1b">

After obtaining the raw CSV file from [cbioportal](https://www.cbioportal.org/). Does it need further processing to get the dataset_csv [datasets_csv/metadata/tcga_blca.csv](https://github.com/mahmoodlab/SurvPath/tree/main/datasets_csv/metadata)?

In addition, in tcga_blca.csv file, what is the difference between a **survival_months** | **survival_months_dss** | **survival_months_pfi**?

Looking forward to your reply！
@guillaumejaume @ajv012

**Comment by ajv012** [comment]
Thanks for your interest in our project! 

To answer your first question, we accessed the survival data from [UCSC Xena](https://xenabrowser.net/datapages/). We used cbioportal to access patient clinical data such as stage, grade, sex, etc. We did not use the survival data from cbioportal. 

For your second question, there are different kinds of survival types. DSS stands for "disease specific survival" and PFI stands for "progression free survival" You can read more about them as well as their benefits and pitfalls [here](https://www.cell.com/cell/fulltext/S0092-8674(18)30229-0). In our study we use disease specific survival, which has also been done at [here](https://github.com/mahmoodlab/PANTHER) and [here](https://github.com/mahmoodlab/MMP).

**Comment by adiv5** [comment]
On the UCSC Xenabrowser, We already has the Phenotypic data along with the survival information right. I wanted to know why do we go to CBioportal for the clinical data?
